import Typography from '@mui/material/Typography';

import Meta from '@/components/Meta';

import Paper from '@mui/material/Paper';
import Divider from '@mui/material/Divider';
import HTMLFlipBook from 'react-pageflip';
import parse from 'html-react-parser';

import { useLocation } from 'react-router-dom';


import "../pages.css";

function Page1() {
  
  const {state} = useLocation();
  
  let startPage: number = 0;
  
  if(state){
	  startPage = state.result.id as number;
	  console.log("State from page 2", state.result.id)
  }
  
  //console.log("State from page 2", state.result.page_number)
  
  interface pageObj {
	id: number;
	content: string
	page_number: string
  }
  
  //console.dir(Object.entries(signesData));
  //console.dir(Object.keys(signesData));
  //const signesDataArr = Object.entries(signesDataRaw);
  //const pagesDataArr = Object.entries(pagesDataRaw);
  //console.log(signesDataArr[0][1][0]);
  //console.log(signesData);

  let pagesData: pageObj[] = [
		
		{
		  id: 1,
		  content: "<h2>SIGNIFICATION DES MAISONS GEOMANCIQUES</h2><h2>PREMIERE MAISON GEOMANCIQUE \"GBE-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m1.svg\"/><h2>Son signe: \"OGBE\"</h2><img classname=\"page-image\" src=\"./geomancie/s1.svg\"/><p>La première maison géomancique est celle régie par \"GBE-MEDJI\" encore appelée \"DJOGBE\". Son signe Ogbé ou Gbé s'y trouve en double, donc en dignité et en puissance maximum. Cette maison commande le jour et tout ce qui s'y passe. C'est elle qui régit le monde visible. Son signe Ogbé correspond à la figure géomancique la \"voie\" . Astrologiquement commandée par le signe de Cancer, elle est sous la domination de la lune. De prédominance élementaire eau, on peut aussi la comparer à l'arcane II du tarot la \"PAPESSE\".<p>Cette maison est celle de la bonne influence de l'élément eau, recevant les aspects bénéfiques de la planète lune et de son signe le cancer. A ce titre, elle est légèrement défavorable du fait de l'influence lunatique qui cause une transformation sans cesse de tout ce qui est , entraînant ainsi des retards pour empêcher une réalisation définitive des choses. Elle indique l'instabilité, les changements et la mobilité de tout ce qui est. Très favorable à la durée de l'existence, elle ne donne cependant pas la vitalité et entraîne le lymphatisme. Elle fait faire des voyages et des déplacements fréquents. Donne de l'inertie, la passivité et cause de la paresse. Elle fait aimer son intérieur, le calme, la paix; donne de l'imagination et une tendance à la rêverie. Favorable à la progéniture, surtout au sexe féminin; elle rend dévoué, ce qu n'empêche pas l'égoïsme. Elle donne également des sautes d'humeurs, une santé chancelante malgré une longévité probable.",
		  page_number: "91"
		},
		{
		  id: 2,
		  content: "<p>Elle est la maison de la chance pure, des aides mystérieuses, occultes et providentielles. Elle permet d'être toujours aidé par le sort et favorise les unions au-dessus de sa situation. Donne une possibilité de d'héritage, de donation ou de legs. Elle est l'indication des choses mystérieuses dans un sens favorable pour le natif ou le consultant dont la réussite comme la fortune seront tributaires de la chance et du sort.</p><br><p><strong>En consultation :</strong> cette maison ou son signe indique les déplacements, les voyage, les réunions et la popularité. Elle signale la mise en chantier, le début d'un projet ou la mise en exécution de quelque chose. Elle est l'indicationd'une chance d'une aide providentielle, occulte ou mystérieuse, d'un concours de circonstances ou du sort qui favorisera la réussite de quelque chose, d'un projet malgré des retards possibles, une chose cachée, révélée, apportant force et assurance pour triompher du mal. Indique aussi la féminité, l'amour maternel, la gestation, la soumission, la modération, le calme. Signale une réunion, les réunions politiques, les assemblées populaires où l'on discute en vue de prendre des décisions importantes. C'est aussi le suffrage universel ou l'opinion populaire, etc. Une voie objective ou morale, une route, une idée et cela dans un sens bénéfique.</p><br><p><strong>Cette maison est en rapport avec :</strong> les routes, les rivières et les cours d'eau, les canaux et toutes les voies navigables. Les semences et par extension, tous projets éphémères qui passent comme l'eau.</p><br><p><strong>Représente :</strong> les poètes, les politiciens, les artistes mystérieux ou les écrivains mystiques, toutes les professions féminines et surtout celles qui touchent les liquides ou qui demandent de l'imagination. Les fonctionnaires, cultivateurs, employés de pompes funèbres, cheminots et tout ce qui s'apparente à la route, comme les transports, camionneurs, facteurs P.T.T., mariniers, acteurs en tournée, routiers, colporteurs, cyclistes, etc.</p><br><p><strong>Feuilles liturgiques :</strong> affamà, feniè (manioc), kotama, zùno.</p><br><p><strong>Couleur préférée :</strong> le blanc</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou bonnes influences de cette maison ou de son signe: les sacrifices \"Vonssissas et Adras\", les cérémonies et prières sont à adresser aux fétiches (divinité ou esprit de référence immédiate) Dan-Tohossou ou leurs dérivés.",
		  page_number: "92"
		},
		{
		  id: 3,
		  content: "<h2>DEUXIEME MAISON GEOMANCIQUE \"YEKOU-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m2.svg\"/><h2>Son Signe : \"YEKOU\"</h2><img classname=\"page-image\" src=\"./geomancie/s2.svg\"/><p>La deuxième maison géomancique est celle que commande \"YEKOU-MEDJI\" . Son signe YEKOU, qui correspond à la figure géomancique \"le peuple\" s'y trouve en double, en dignité et en puissance. \"YEKOU-MEDJI\" commande la nuit, l'ombre, l'obscurité et tout ce qui s'y passe. Elle régit le monde invisible et le royaume de l'au-delà (les morts). Astrologiquement, cette maison dépend de la lune et de son domicile le cancer. Son signe de prédominance élementaire eau , s'apparente à l'arcane 18 du tarot \"LA LUNE\".<p>Maison de la mauvaise influence lunaire, l'élément eau, se trouvant ici très mal aspecté par la lune, et son signe cancer, dispense des effets maléfiques. Elle est, par conséquent, le contraire de la première maison. A ce titre, elle est la maison de la déception, de la hantise, des soucis, des inquiétudes tant imaginaires que réels. Subissant les effets de la lune , elle indique aussi des choses mystérieuses, mais dans un sens mauvais et fâcheux pour le natif ou le consultant. Maître de l'obscurité et de l'invisible, elle indique la fausse sécurité, les idées sombres et les tourments. Elle signale que l'ensemble de la destinée sera assez médiocre et que les choses ne s'arrangeraient pas comme on serait en droit de l'espérer et qu'il faut s'attendre à des déceptions dans tous les domaines. Elle est l'indication de fréquents heurts et des discordes avec l'entourage, par la faute du natif ou du consultant dont l'esprit mal tourné ne voit pas la vie sous son vrai angle. Aussi, la crainte, les fausses idées, la hantise, l'inquiétude, l'angoisse et quelques fois les ennemis tant réels qu'imaginaires feront que l'individu sera continuellement en lutte contre lui-même.<p>Physiquement, cette maison ou son signe marque la neurasthénie, les maladies ou les accidents causés par l'eau. Elle signale une mauvaise circulation du sang pour une femme à qui elle peut causer des avortements. Dans le domaine sentimental, elle indique la duplicité, ou même l'adultère ou l'union double. Elle peut causer parfois la folie.</p><br><p><strong>En consultation :</strong> Elle indique le plus souvent un consultant inquiet, tourmenté, anxieux ou déçu. Elle signale tout ce qui se passe dans la nuit, tout ce qui se fait caché ou est caché dans l'ombre ou qu'on garde secret. Elle indique un scandale, une diffamation ou un secret qu'on voile. Elle est l'indication des réunions secrètes, de la conspiration et de l'espionnage. Elle signale aussi les voyages, les allées et venues, les tracas. Elle marque les mauvaises mères, les prostituées, la foule et le public en général. Elle signale également les morts ou",
		  page_number: "93"
		},
		{
		  id: 4,
		  content: "<p>les ancêtres. Elle marque souvent une déception , un mauvais concours de circonstances, une mauvaise révélation ou une mauvaise nouvelle empêchant ou contrariant un espoir attendu, un changement, une mauvaise affaire, des disputes, etc. Une mauvaise voie, physique ou morale, une mauvaise idée, manière, un comportement voilant, obstruant ou contrariant et empêchant une révélation, l'aboutissement ou la réussite de quelque chose.</p><br><p><strong>Cette maison est en rapport avec :</strong> la mer, les océans, les grands lacs, les forêts et les plaines, la foule, les assemblées de tout genre, les choses étranges, les étangs, les lieux cachés ou humides.</p><br><p><strong>Représente :</strong> les commis voyageurs et tous ceux dont les le travail nécessite un déplacement continuel. Les marins, les pêcheurs, camelots, forains, speakers, avocats, tout ce qui a trait à la navigation, le marché, les commerces, chroniqueurs et téléphonistes, etc.</p><br><p><strong>Feuilles liturgiques :</strong> sisrèmà, gbagbada, ahwiman, yasséaku (fon).</p><br><p><strong>Couleur préférée :</strong> le noir.</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou bonnes influences de cette maison, les dieux de référence sont : Tohossou, Dan et surtout les défunts (les morts), les ancêtres à qui elle indique des prières, cérémonies sacrifices \"Vonsissas ou Adras\" selon les cas.",
		  page_number: "94"
		},
		{
		  id: 5,
		  content: "<h2>TROISIEME MAISON GEOMANCIQUE \"WOLI-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m3.svg\"/><h2>Son signe: \"WOLI\"</h2><img classname=\"page-image\" src=\"./geomancie/s3.svg\"/><p>La troisième maison géomancique est gouvernée par \"WOLI-MEDJI\" dont le signe \"WOLI\" qui correspond à la figure Conjonction encore appelée Rencontre, s'y trouve en dignité et en puissance maximum. Sa dominante élementaire est la Terre. Sous la dépendance astrologique de Mercure, elle est commandée par les gémeaux. En taromancie, elle s'apparente à l'arcane trois , \"L'EMPEREUR\".<p>L'heureuse influence de Mercure dans le signe des gémeaux permet à l'élément Terre de dispenser des effets favorables dans cette maison. Ainsi, cette maison confère aux natifs confère une compréhension consciente et inconsciente des choses mystérieuses et cachées, des dons naturels pour le mystère et le mysticisme, une aptitude particulière pour toutes les recherches. Aussi, l'influence de Mercure dans cette maison confère à celle-ci du fait que le natif manque de confiance soi, par pudeur, par crainte, par timidité. Tout en accordant une vie relativement facile, elle octroie beaucoup de sympathie et favorise les relations. Elle indique aussi l'ambition et l'orgueil, fait aimer les plus jeunes que soi et se montre favorable aux parents auxquels elle donne une possibilité de jumeaux.<p>Cette maison ou son signe accorde aux natifs un caractère subtil, une facilité d'adaptation, de l'intuition, de la finesse, du tact et un esprit de diplomatie. Le caractère est ingénieux, analytique, avec une habileté intellectuelle, une déduction rapide et prompte. Elle accorde aussi l'éloquence ou tout au moins une facilité d'expression, d'élocution. Elle est l'indication des amitiés et des associations fructueuses et profitables. Elle accorde également une possibilité de nombreux voyages. Mais sur le plan matériel, cette maison reste moins favorable, car elle crée une situation instable du fait que le natif est prodigue ou qu'il a tendance à disperser ses efforts. Physiquement, le natif, souvent sur les nerfs est menacé d'asthénie, par le fait qu'il ne se ménage pas ou qu'il ne sait pas se détendre.</p><br><p><strong>En consultation :</strong> cette maison ou son signe indique les activités, les rencontres, les associations, un projet heureux même avec un retard probable. Elle signale les luttes, la victoire, des difficultés ou un empêchement pour un voyageur. Une mortalité ou un décès, un danger pour la femme enceinte, une malchance pour un prisonnier, un profit pour un conspirateur ou un traître. Indique une association de forces contre le destin, ou pour la réussite de quelque chose. Le",
		  page_number: "95"
		},
		{
		  id: 6,
		  content: "<p>report ou l'ajournement, des retards dans l'accomplissement d'un évènement ou de quelque chose, et un risque de morsure de serpent, une prise au piège.</p><br><p><strong>Cette maison est en rapport avec :</strong> les salles de ventes, les lieux d'assemblées, les amphithéâtres, les grandes écoles, les grands magasins, entrepôts, les cavaliers, les grands animaux, les serpents, etc.</p><br><p><strong>Représente :</strong> les orateurs, les philosophes, les compositeurs, les écrivains talentueux, les scientifiques, les journalistes, les gens de lettres, la jurisprudence, les industriels, la diplomatie et le pouvoir financier, etc.</p><br><p><strong>Feuilles liturgiques :</strong> wlékpékpéman (fon).</p><br><p><strong>Couleur préférée :</strong> le marron tirant sur le rouge.</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou bonnes influences de l'esprit de référence ou dieu, ce sont \"Ogu\" et les morts auxquels il faut adresser les prières, cérémonies (Vonssissas ou Adras), selon le cas.",
		  page_number: "96"
		},
		{
		  id: 7,
		  content: "<h2>QUATRIEME MAISON GEOMANCIQUE \"DI-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m4.svg\"/><h2>Son signe: \"DI\"</h2><img classname=\"page-image\" src=\"./geomancie/s4.svg\"/><p>Gouvernée par \"DI-MEDJI\", la quatrième maison géomancique a pour signe \"DI\" qui correspond à la figure Carcer ou Prison . \"DI\" s'y trouve en dignité et en puissance maximum. Sa dominante élementaire est la terre. Régie astrologiquement par la planète Saturne, elle est commandée par Capricorne, son signe du Zodiaque. Dans le tarot, sa correspondance est l'arcane 14, \"LA TEMPERANCE\".<p>Subissant les mauvais effets de la planète Saturne dans le Capricorne, l'élément Terre a dans cette quatrième maison, une influence des plus néfastes. Elle est le contraire de la maison précédente. Cette maison est donc de nature rétentrice, concentrée, prudente et réservée. Causant des alternatives de hauts et de bas, elle prévoit du retard dans la satisfaction des désirs du natif ou du consultant. Conseille la patience, la réflexion et indique que la ruse serait meilleure que la violence si l'on veut aboutir à une bonne fin. Cette maison étant celle des difficultés, des entraves, des contraintes, elle entraîne l'immobilité ou la stagnation par le fait que les obstacles se renouvellent sans cesse. On pourrait même dire qu'elle est contraire à tout changement. C'est la stabilité totale. Elle entraîne aussi la solitude. Oblige à déployer des efforts importants pour n'obtenir que de très maigres résultats. Devant cette fatalité, le natif se laisse aller au découragement, au repliement sur lui-même. Elle commande le repos, la patienceet dit que le temps est un grand maître. Elle est aussi l'indication d'une pente dangereuse sur laquelle se trouve le natif ou le consultant, et signale qu'il est nécessaire de faire attention dans tous les domaines, car elle influence en mal le sentiment, la santé, le moral comme les affaires d'argent. Physiquement, elle indique les maladies de langueur, chroniques et de longue durée.</p><br><p><strong>En consultation :</strong> Cette maison ou son signe indique les dangers, les entraves, les contraintes et les difficultés de toutes sortes, donnés ou reçus. Elle signale la perte prématurée des parents, l'échec, l'insuccès, les chutes ou mmême la révolte. Elle indique le célibat, les mauvaises unions ou les unions mal assorties, le concubinage et même le veuvage. Elle signale aussi les ruines, les complots, la traîtrise, les difficultés légales ou pénales (prison), les contraintes, les hostilités, la sévérité, l'isolement moral ou physique. Indique la réconciliation des ennemis, une bonne route pour un voyageur, désigne un chef triste. Une libération suivie de claustration pour un prisonnier, etc. Elle indique le plus souvent un",
		  page_number: "97"
		},
		{
		  id: 8,
		  content: "<p>consultant triste, soucieux, en difficulté ou malade.</p><br><p><strong>Cette maison est en rapport avec :</strong> les tribunaux, les prisons, les hôpitaux, les cliniques, les cloîtres, les cimetières, les lieux obscurs, etc. <br><p><strong>Représente :</strong> les ingénieurs, les chimistes, les mathématiciens, astronomes, astrologues, géôliers, les fossoyeurs, mineurs, les gardiens de nuit, les mendiants, les révoltés, les policiers, les fonctionnaires, les archivistes, les emplois de bureau sédentaires, les traîtres, les noctambules solitaires, les espion, les prisonniers réels ou tous ceux qui manquent de libre arbitre moralement.<:p> <br> <p><strong>Feuilles liturgiques :</strong> désréguè ou désréssiguè-man (fon)</p> <br> <p><strong>Couleur préférée :</strong> Le noir et les bigarrures. Le jaune et le rouge quelquefois pour les sacrifices aux femmes.</p> <br> <p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou bonnes influences de cette maison ou de son signe, adresser les sacrifices, cérémonies ou prières à Nà-Kinnessi et Sakpata (dieux ou esprits de référence).",
		  page_number: "98"
		},
		{
		  id: 9,
		  content: "<h2>CINQUIEME MAISON GEOMANCIQUE \"LOSSO-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m5.svg\"/><h2>Son signe : \"LOSSO\"</h2><img classname=\"page-image\" src=\"./geomancie/s5.svg\"/><p>Commandée par \"LOSSO-MEDJI\", la cinquième maison géomancique a pour signe \"LOSSO\" qui correspond à la figure Fortune mineure. De prédominance élémentaire feu, elle est régie par le soleil et son domicile astrologique est le Lion. En cartomancie, elle a pour équivalence l'arcane 19 \"LE SOLEIL\".<p>Contrairement à la maison suivante, l'élément feu se trouve dans celle-ci défavorable. Recevant les mauvais aspects du soleil et de son signe astrologique le Lion, cette cinquième maison géomancique expose aux influences néfastes de son élément. Cependant, elle reste assez favorable sur le plan matériel dans un sens général. Elle indique l'acummulation des obstacles et l'instabilité. Entraînant souvent des dépenses inutiles, elle expose à des heurts et des fâcheries avec l'entourage pour des raisons d'intérêt, cela surtout avec la famille. Elle est l'indication des excès, car le coeur domine la tête et l'on suit ses instincts, ses impulsions bonnes ou mauvaises, ce qui est souvent fâcheux, car cela entraîne parfois la violence, la discorde, la jalousie et la licence. Cette maison indique des difficultés pour la mère du natif et parfois même la mort de celle-ci. Elle est également défavorable pour l'union, l'amour ainsi que le sentiment en général, par le fait du caractère égoïste et irrascible du natif qui est large pour lui-même; présomptueux, il est souvent sans générosité pour autrui. Du point de vue matériel, elle expose à une perte de fortune, à une vie de luxe pas toujours raisonnable ou sans rapport avec les moyens du natif. Aussi, recommande-t-elle la prudence du point de vue sentimental et financier.</p><br><p><strong>En consultation :</strong> indique la violence et l'agressivité subies ou données. Cette maison ou son signe annonce des difficultés dans un domaine comme dans un autre. Elle est l'indication d'un malheur imminent, de dangers graves, pouvant entraîner quelque fois la mort. Elle annonce des obstacles, des déboires ou des heurts avec l'entourage ou avec la famille. Une perte de fortune ou des dépenses d'argent excessives dues à une situation compromettante, à l'adultère qui coûte, etc. Elle indique que le but visé est trop difficile à atteindre pour les moyens dont dispose le questionneur, ou que des efforts trop importants seront consentis pour un intérêt médiocre. Et même s'il y a succès, c'est toujours instable, du fait d'un manque de coordination entre les forces en présence. Signifie aussi discorde, envie, colère, disputes. Dommage pour un malade, fièvre ou congestion. Un espoir qui se dérobe.",
		  page_number: "99"
		},
		{
		  id: 10,
		  content: "<p><strong>Cette maison est en rapport avec :</strong> les grands appartements, la bijouterie d'art, la loterie, les caprices de la fortune, les jolies fleurs, tout ce qui est riche et haut en couleur, particulièrement le rouge. Les contrées chaudes.</p><br><p><strong>Représente :</strong> les aventuriers, les propagandistes, les gens autoritaires ou ayant des fonctions avec le public. Les leaders politiques, les chefs d'entreprise, pionniers, joiailliers, les métiers qui comportent une direction. Cette maison représente aussi, tout ce qui est masculin, tyrannique, expansif, bruyant et éclairé. Les arrivistes, les gens célèbres our riches, les assemblées politiques, etc.</p><br><p><strong>Feuilles liturgiques :</strong> kpaklessi (fon) xèxèman, dindinfundin, amadjin.</p><br><p><strong>Couleur préférée :</strong> le rouge</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou bonnes influences de cette maison ou de son signe, adresser les prières, cérémonies, sacrifices (Vonsissas ou Adras) à Hêbiosso (dieu de la foudre), esprit de référence de l'élément. Autres esprits à associer: Dan, Nà et Gu.",
		  page_number: "100"
		},
		{
		  id: 11,
		  content: "<h2>SIXIEME MAISON GEOMANCIQUE \"WINLIN-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m6.svg\"/><h2>Son signe : \"WINLIN\"</h2><img classname=\"page-image\" src=\"./geomancie/s6.svg\"/><p>Maître de la sixième maison qui porte son nom, \"WINLIN-MEDJI\" a pour signe \"WINLIN\", correspondant de la figure géomancique \"Fortuna Major\" ou encore Fortune majeure. Dominée par l'élément feu, elle dépend astrologiquement du soleil, et de son domicile le Lion. Du point de vue cartomancie, on peut la comparer à l'arcane 21 ou précisément le 1 dont il est l'équivalent, c'est-à-dire \"LE BATTELEUR\".<p>Contrairement à la maison précédente, dans celle-ci, l'élément feu, recevant les meilleurs aspects du soleil et de son domicile le Lion, dispense ses influences les plus heureuses en libérant des énergies bénéfiques. Maison bénéfique par excellence, elle est par conséquent celle de l'intelligence créatrice, du savoir-faire et de l'habileté. Elle donne de la confiance en soi, de l'éloquence et des aptitudes réelles pour la compréhension naturelle du bien, du vrai et du beau. C'est aussi celle du succès facile et complet sans grand effort. Les résultats obtenus sont toujours supérieurs à l'espoir. Elle permet de triompher de nombreux obstacles en accordant des amitiés, des appuis, et des secours puissants. Elle représente le bonheur acquis par l'intelligence, le travail, la droiture et la bonté. Elle donne aussi des conceptions philosophiques, un esprit puissant et éclairé qui voit grand et ne s'encombre pas de détails, de l'intuition, de la déduction et une analyse facile. Elle est celle de l'élevation constante du natif. Tout en étant très favorable aux enfants nés, elle donne de la joie à ses sujets. Permettant de spéculer avec chance, elle accorde une vie de bonheur, de plaisirs, en un mot de triomphe et de réussite.</p><br><p><strong>En consultation :</strong> cette maison ou son signe indique une réussit totale ou facile, un triomphe, une victoire ou un succès assuré. Elle signale aussi un secours puissant concourant à la résussite, au triomphe ou aidant à une victoire. C'est aussi le recouvrement d'un objet perdu ou volé, le retour de l'exilé ou une sortie de prison. Parfois, elle signale un dommage pour le malade et le voyageur. Elle est souvent l'indication que l'interessé a emmengasiné assez de réserves qui lui permettront de faire face à des difficultés même soudaines, et qu'il peut agir seul sans compter sur autrui.</p><br><p><strong>Cette maison est en rapport avec :</strong> l'aristocratie héréditaire, les chefs, la richesse ancestrale, les bourgeois, les hauts fonctionnaires, notamment ceux du minitère",
		  page_number: "101"
		},
		{
		  id: 12,
		  content: "<p>des finances, les monuments artistiques, les oeuvres d'art, les appartements somptueux. Les beaux parcs, l'or, les trésors cachés, le jaune, l'ombre des arbres. Les assemblées célèbres, les réunions brillantes, les cérémonies. La célébrité, la philantropie, tout ce qui est brillannt la chaleur, etc.</p><br><p><strong>Représente :</strong> les hauts dignitaires, les hommes illustres, les acteurs célèbres, archéologues, antiquaires, le chef écouté et aimé, le père, les princes, le pouvoir, les chefs, le roi.</p><br><p><strong>Feuilles liturgiques :</strong> Godokô, gninsikin (fon), mafowokà omomi (yoruba)</p><br><p><strong>Couleur préférée :</strong> Les choses bigarrées, multicolores, rayonnantes, colorées, éclairées</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou les bonnes influences de cette maison ou de son signe, les cérémonies, prières, sacrifices (Vonsissas et Adras) sont à adresser à Hêbiosso, dieu ou esprit de référence immédiate, sans oublier d'associer Sakpata, Kinnessi et Dah.",
		  page_number: "102"
		},
		{
		  id: 13,
		  content: "<h2>SEPTIEME MAISON GEOMANCIQUE \"ABLA-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m7.svg\"/><h2>Son signe : \"ABLA\"</h2><img classname=\"page-image\" src=\"./geomancie/s7.svg\"/><p>Seigneur de la septième maison, \"ABLA-MEDJI\" dont le signe \"ABLA\" correspond à la figure géomancique Liesse encore appelée \"Joie\", est de prédominance élementaire Air. Astrologiquement, il dépend de la planète Vénus et de son signe zodiacal la Balance. En cartomancie, elle a pour équivalence l'arcane 7, \"LE CHARIOT\".<p>Recevant les meilleurs aspects de la planète Vénus et de son domicile la balance, l'élément air se trouvant ainsi bien aspecté dans cette maison, dispense des effets favorables et bénéfiques. A ce titre, cette maison donne une égalité d'âme, l'amour de la forme, du vrai et du beau. Elle indique une expansion matérielle ou morale, en raison de l'abondance exubérante de l'énergie dispensée. Les obstacles sont toujours renversés, même à la dernière minute, car le destin protège le sujet . Elle marque l'harmonie du corps, du coeur et de l'esprit, puis permet une maîtrise des passions, mais rend quelquefois présomptueux. Les activités et le travail du natif lui permettent de réaliser ses désirs et d'atteindre le but fixé par la voie choisie. Le caractère gai, amical et bienveillant de celui-ci lui facilite les contacts sociaux et l'aide à réussir, grâce aux concours des amis. Cette maison accorde sinon la fortune, tout au moins une aisance relative aux possibilités du sujet, en lui accordant la joie et le bonheur. Elle préserve toujours dans les moments difficiles et favorise la durée de l'existence et la victoire sur tout ce qui gêne.</p><br><p><strong>En consultation :</strong> cette maison ou son signe indique les difficultés, les complots, les jalousies dont on triomphe, ou annonce une victoire certaine, dans un domaine comme dans un autre. Elle signale que le consultant en difficulté est préservé par le destin ou recevra bientôt une aide providentielle pour sa libération. Annonce également un succès, une réussite sans gros efforts. Un objet de prix pour le consultant. Bonne nouvelle imprévue. Conquête, joie, etc. Signale, en outre, que le consultant se trouve dans la bonne voie, et qu'il recevra une aide providentielle pour la réussite ou la réalisation de ses désirs.</p><br><p><strong>Cette maison est en rapport avec :</strong> les arcs de triomphe, les portiques, les temples, les endroits où l'on s'amuse, les édifices municipaux, le ciel, les pyramides, les montagnes boisées. Le camping, l'embonpoint, les relations agréables, la paix, donc le calme et la tranquilité.",
		  page_number: "103"
		},
		{
		  id: 14,
		  content: "<br><p><strong>Représente :</strong> les éditeurs, organisateurs de fêtes, le haut clergé, tout ce qui est riant, les musiciens, les artistes, les concerts, les bals, la magistrature, les sociétés de bienfaisance, les sportifs, les restaurateurs.</p><br><p><strong>Feuilles liturgiques :</strong> Weeya (yoruba), davonumà (fon).</p><br><p><strong>Couleur préférée :</strong> Bleu clair (Couleur du ciel)</p><br><p>Pour conjurer les effets maléfiques ou s'attirer les influences bénéfiques de cette maison : adresser les prières, cérémonies, sacrifices (Adras ou Vonssissas) aux dieux Yalodé, Kpovodoun, Dan et Sakpata.",
		  page_number: "104"
		},
		{
		  id: 15,
		  content: "<h2>HUITIEME MAISON GEOMANCIQUE \"AKLAN-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m8.svg\"/><h2>Son signe : \"AKLAN\"</h2><img classname=\"page-image\" src=\"./geomancie/s8.svg\"/><p>Maître de la huitième maison géomancique, \"AKLAN-MEDJI\" qui veut dire \"AKLAN\" deux fois, s'y trouve en dignité et en puissance maximum. Son signe \"AKLAN\" correspond à la figure géomancique la Tristesse. De prédominance élementaire Terre, elle est astrologiquement régie par la planète Saturne et le signe de Verseau. En taromancie, son équivalence est l'arcane 13 (sans nom). \"LE SQUELETTE FAUCHEUR\".<p>La huitième maison géomancique est reconnuecomme celle de la mort. Curieusement, elle coincide avec la huitième maison astrologique. Le nom \"AKLAN\" que porte son signe, le signifie bien, puisqu'il veut dire séparation. La séparation du corps et de l'esprit. Les jumeaux qui le symbolisent ne veulent pas forcément dire deux choses, comme on a souvent tendance à le croire, mais signifient plutôt que ceux-ci, ensemble dans le sein de leur mère, se sépareront une fois venu au monde. De même, l'esprit et le corps ensemble durant toute la vie, se sépareront au moment de la mort.<p>L'élément Terre, dans cette maison où il reçoit les mauvais aspects de la planète Saturne et de son signe le Verseau, ne peut que dispenser les influences les plus néfastes. De nature concentrée et rigide, elle implique la froideur et la mélancolie, d'où probablement son nom, de tristesse. Elle signifie aussi la transformation, un changement en bien ou en mal de tout ce qui existe. Elle régit la fatalité, le sujet se laissant dominer par les évènements et les gens sans vouloir réagir. Aussi, subit-il les épreuves sans trop chercher a en échapper. Elle donne un caractère renfermé, avec le besoin de rechercher la vérité dans tous les domaines. Elle est l'indication du recueillement et de la solitude. Cette maison provoque les machinations, les actes injustes, les hostilités pouvant gâcher la vie du sujet. Elle est la maison de la contrainte et des tromperies amoureuses. Le sujet se déprime très vite et se fatigue pour rien, ses occupations étant souvent d'ordre intérieur. Il vit dans les souvenirs et rarement au moment présent. Cette maison maintient l'esprit dans les ténèbres, donne l'hypocondrie, la mysanthropie, le pessimisme, la dépression, le repliement sur soi-même et l'amaigrissement.</p><br><p><strong>En consultation :</strong> cette maison ou son signe annonce des choses sombres et tristes. Elle signale la mort ou les choses entraînant ou ayant trait à la mort. Elle indique les deuils, les décès, les séparations douloureuses, les veuvages, les dangers, le découragement, les déceptions. Elle annonce également une",
		  page_number: "105"
		},
		{
		  id: 16,
		  content: "<p>transformation, une régénération, un changement d'état ou de fait. Dans la plupart des cas, c'est l'accélération de la chose annoncée bonne ou mauvaise. Indique un dommage certain pour la femme enceinte et son foetus, l'anéantissement de quelque chose, l'arrestation du voleur, un dommage pour un prisonnier, le naufrage en mer ou sur l'eau pour un voyageur, en tout cas la perte certaine de quelque chose. Représente un consultant pensif, triste ou un avare.<p><br><p><strong>Cette maison est en rapport avec :</strong> les cimétières, les choses ou les lieux sinistres, sombres ou tristes. La mort et les choses s'y rapportant. Les monastères, les couvents, la vieillesse.</p><br><p><strong>Représente :</strong> L'hermite, le prêtre, l'apôtre, l'idéaliste, le savant, l'agriculteur, l'ingénieur ou le grand-père.</p><br><p><strong>Feuilles liturgiques :</strong> Koklodinkpadjê, klonman, assobokan (fon).</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvais ou les bons effets de cette maison ou de son signe, faire \"Vonssissas Kudiô\". Adresser les prières et sacrifices (Vonssissas ou Adras) aux divinités (fétiches) Hoho (jumeaux), Lègba, Hêbiosso et Loko.",
		  page_number: "106"
		},
		{
		  id: 17,
		  content: "<h2>NEUVIEME MAISON GEOMANCIQUE \"GUDA-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m9.svg\"/><h2>Son signe: \"GUDA\"</h2><img classname=\"page-image\" src=\"./geomancie/s9.svg\"/><p>La neuvième maison géomancique est dirigée par \"GUDA-MEDJI\". Elle s'y trouve en dignité, en double et en puissance maximum. Son signe \"GUDA\" correspond à la figure Cauda Draconis ou la queue du dragon. Astrologiquement régie par Vénus et le signe du Taureau, son signe est de prédominance Terre. En taromancie, elle a pour équivalence l'arcane 16 \"LA MAISON DIEU\".<p>Maison de la mauvaise influence de l'élément Terre dans le signe du Taureau où il subit les aspects néfastes de la planète Vénus, celle-ci dispense les effets les plus pernicieux.<p>Cette maison libère des fluides inférieurs qui poussent le sujet à agir souvent contre lui-même. Le natif ou le consultant désire du changement sans savoir le but qu'il veut atteindre. L'action dissolvant e de cette maison pousse toujours à rompre tout ce qui existe. A ce titre, elle est la maison de la catastrophe au sens le plus significatif du mot. Elle est l'indication de l'échec, de la ruine, des heurts importants dans le cours de l'existence du sujet. Elle signale les accidents à redouter et l'effondrement des espoirs. Très peu favorable aux affaires et aux sentiments dans un sens général, elle apporte des coups subits du sort dans un sens mauvais. Causant des pertes de situations, la mort brutale, des contrariétés de toutes sortes, la séparation des conjoints, l'adultère, les ruptures d'association, elle provoque l'accident d'une manière inattendue. Les forces rampantes et corruptrices qu'elle libère, empoisonnent l'âme et le corps puis prédisposent le sujet aux mensonges, à la médisance et à toutes les perversions qui lui font cortège.</p><br><p><strong>En consultation :</strong> cette maison ou son signe signale les abus, les choses violentes, subites ou données, les heurts avec l'entourage, les inimitiés agissantes et violentes, de même que les accidents de toutes natures. Elle indique une perte dans un domaine comme dans un autre, ou un changement de route se traduisant souvent par l'effondrement des espoirs, les ennuis dans tous les domaines, des bouleversements subits de situation, la mort accidentelle, subite ou violente. Elle signale également la maladie, les difficultés sentimentales, l'adultère, le divorce ou le veuvage dans l'union. Elle indique, en outre, la faillite ou la ruine dans les affaires, des erreurs graves et irréparables que commet le sujet. Dans tous les cas, cela signifie un changement inattendu mais malheureux, du fait que l'idée est mauvaise et condamnable; sa réalisation même partielle, promet un résultat toujours négatif pour le consultant.",
		  page_number: "107"
		},
		{
		  id: 18,
		  content: "<p>Parfois, sous un bon aspect, elle indique encore une libération ou une amélioration dans la santé d'un malade. Un projet brutalement arrêté, un coup de théâtre ou une chose inattendue.</p><br><p><strong>Cette maison est en rapport avec :</strong> les éboulements de terrain, les chutes, les accidents de masse. Les catastrophes de toutes sortes, les avalanches, les mines, les grottes, les poisons, les puits, les caves.</p><br><p><strong>Représente :</strong> les gens de mauvaise vie. Ceux qui vivent du vice des foules. Les mineurs, fondeurs, détectives, agents secrets, espions, entremetteurs, proxénètes.</p><br><p><strong>Feuilles liturgiques :</strong> Lidji - Agnaman (fon)</p><br><p><strong>Couleur préférée :</strong> le noir - le rouge et aussi le blanc.</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou les bonnes influences de cette maison ou de son signe : (Hê nan - diôku - Sa Gu ovi); adresser les prières, cérémonies, sacrifices (Vonssissas ou Adras) aux divinités : Gu, Lègba, Aguê, puis associer aussi Dan-Hêbiosso et Ké.",
		  page_number: "108"
		},
		{
		  id: 19,
		  content: "<h2>DIXIEME MAISON GEOMANCIQUE \"SA-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m10.svg\"/><h2>Son signe: \"SA\"</h2><img classname=\"page-image\" src=\"./geomancie/s10.svg\"/><p>Maître de la dixième maison, \"SA-MEDJI\" a pour signe \"SA\". Celui-ci s'y trouve en double, c'est-à-dire en dignité et en puissance maximum. Ce signe correspond à la figure Tête du Dragon. Astrologiquement gouverné par le signe des Gémeaux et régi par Mercure, il est de prédominance air. En taromancie, on peut le comparer à l'arcane 17, \"L'ETOILE\".<p>On peut aussi dire sans se tromper que cette maison fait partie des plus bénéfiques, car la combinaison Mercure-Gémeaux permet à l'élément air de libérer des effets très favorables.<p>D'action lente, progressive, paisible mais sûre, la dixième maison géomancique est celle de l'espérance. En outre, elle donne de l'intuition, une imagination créatrice, la souplesse d'esprit favorable aux relations et aux déplacements agréables. Elle influence favorablement tout ce qui est intellectuel et cérébral. Maison d'espérance, elle conseille l'optimisme, la patience, le courage et vous dit de ne pas vous laisser abattre, mais d'avoir confiance en l'avenir, car elle libère des fluides protecteurs qui viennent à votre secours pendant les moments de désespoir. Elle est celle de l'aide providentielle et pour peu qu'on croie en elle, elle aide à retrouver la quiétude, l'harmonie et, pour peu qu'on fasse un moindre effort, on est largement récompensé. En conséquence, elle conseille un optimisme agissant, mais non pas un optimisme béat qui attend les alouettes tombées toutes rôties du ciel.<p>Cette maison donne également des prédispositions pour les sciences, les recherches, l'occultisme et la spiritualité sous tous ses aspects. En cela, elle accorde des appuis et des aides occultes très puissants. Très favorable à la longévité, à la santé du malade, à la progéniture, elle rétablit l'harmonie et vous donne la quiétude pendant les moments sombres ou de désordre.</p><br><p><strong>En consultation :</strong> cette maison ou son signe signale les appuis, les aides providentielles ou occultes, données ou reçus pendant les moments difficiles et dans les cas de désespoir. L'espoir dans les moments inquiétants du fait d'un concours de circonstances, d'une aide occulte ou providentielle qui viendra rétablir les choses au mieux pour le consultant. Signale qu'un échec n'est jamais définitif; annonce également que le but visé sera atteint, grâce aux appuis nécessaires dont on profitera. Conseille de ne pas se décourager, prévoit une aide certaine et une perspective de bonheur, en dépit des retards, obstacles et difficultés. Favorable à la santé du malade, elle annonce une",
		  page_number: "109"
		},
		{
		  id: 20,
		  content: "<p>amélioration ou une guérison prochaine par des moyens occultes ou aides de tous ordres. Clémente pour les déplacements, elle est encore favorable pour la femme enceinte dont elle prédit une bonne délivrance. Eclaircissements prochains pour situations sombres ou embrouillées et rétablissement de l'harmonie et de la quiétude dans les cas des difficultés.</p><br><p><strong>Cette maison est en rapport avec :</strong> les médicaments, les montagnes, tous les lieux élevés, les édifices, le serpent de la génèse, l'habitation, les troupeaux, les secrets pénibles, l'occultisme sous tous ses aspects (magie, sorcellerie, etc).</p><br><p><strong>Représente :</strong> les jardiniers, les architectes, les vignerons, la respectabilité et les honnêtes gens.</p><br><p><strong>Feuilles liturgiques :</strong> avôkanfunman, gnonnoussissiman, zomà, hêhêman, adjassi afovê (fon).</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les effets néfastes ou bénéfiques de cette maison ou de son signe, faire des sacrifices à Nà-Tohossou-Yalodé et Sakpata (hénan).",
		  page_number: "110"
		},
		{
		  id: 21,
		  content: "<h2>ONZIEME MAISON GEOMANCIQUE \"KA-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m11.svg\"/><h2>Son signe: \"KA\"</h2><img classname=\"page-image\" src=\"./geomancie/s11.svg\"/><p>Seigneur de la onzième maison géomancique, \"KA-MEDJI\" dont le signe \"KA\" correspond à la figure le \"Rouge\", s'y trouve en dignité et en puissance maximum. Son signe de prédominance élementaire Feu. Cette maison est sous la dépendance de la planète Mars et du signe de Scorpion. En taromancie, elle correspond à l'arcane 8, \"LA JUSTICE\".<p>L'élément Feu, dans cette onzième maison, subissant les mauvais effets de la planète Mars en signe du Scorpion, libère de très mauvaises influences. Aussi, cette maison est-elle celle de la violence, de la révolte, de l'action désordonnée, de l'impulsivité fâcheuse et de l'agressivité. Elle prédispose le sujet à un esprit de révolte dans un but réformateur. Elle détruit dans le but de reconstruire, mais l'esprit vélléitaire l'oblige à changer de but avant d'y être parvenu. Le sujet se trouve ainsi dans un état permanent de révolte contre le destin et contre les hommes. Cette maison expose à la vengeance, à la punition, à la violence et aux dangers de toutes sortes. Elle est aussi celle des ennemis, des inimitiés nombreuses et du mépris. Elle indique les blessures morales et physiques, données ou reçues du fait de l'esprit taquin, perfide, violent, agressif et destructeur du natif. Elle prédispose également le sujet à la vanité, à l'égoïsme et à la jalousie.<p>Sur le plan matériel et financier, elle expose le sujet à une situation instable et à des difficultés dues à l'imprévoyance, à la mobilité d'esprit et à des efforts intermittents. Sentimentalement, elle est encore peu favorable à cause de la passion excessive et de la perfidie du sujet, amenant des heurts et la destruction. D'une résistance physique considérable, le natif est néanmoins prédisposé aux inflammations, aux blessures, aux plaies difficilement guérissables, aux maladies de foie et aux échauffements du sang. Elle indique une mort violente, accidentelle ou brusque.</p><br><p><strong>En consultation :</strong> cette maison ou son signe signale une effusion de sang. Une mort brusque ou accidentelle. Une menace d'accident ou d'un mal foudroyant. Une maladie grave, un emprisonnement prolongé. Indique les ennemis déclarés, les rivaux, les concurrents malhonn=êtes, les voleurs et des choses dangereuses. Signale une extermination des voleurs, annonce une frustration, un procès, une réhabilitation ou une justice rendue. Un profit venant d'une autorité ou d'un chef d'Etat, ou une bonne chose de couleur rouge. Indique que le consultant sera rarement satisfait du résultat obtenu, prévoit une passion, un amour.",
		  page_number: "111"
		},
		{
		  id: 22,
		  content: "<p><strong>Cette maison est en rapport avec :</strong> la révolte populaire, la dictature, la dynamite, les éruptions volcaniques, les usines, les arsenaux, les citadelles, les cités industrielles enfumées, les maisons de couleurs brunes ou noires.</p><br><p><strong>Représente :</strong> les souteneurs, les ouvriers de fer (métalliers) ou de feu, les voleurs, les révolutionnaires en tous domaines, chirurgiens, soldats, espions, les masses ouvrières en révolte, les destructeurs.</p><br><p><strong>Feuilles liturgiques :</strong> sèlèvikè ou sréssèvikè (fon)</p><br><p><strong>Couleur préférée :</strong> Le noir, le rouge et le bleu. Apprécie également ce qui est tacheté.</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou les bonnes influences de cette maison ou de son signe, adresser les prières, cérémonies, sacrifices (Vonssissas ou Adras) aux divinités : Tohossou, Hohovi (jumeaux). Associer les fétiches Hêbiosso, Gu, Lissa, Dan et Loko (Hênan - do Tohossou Gban).",
		  page_number: "112"
		},
		{
		  id: 23,
		  content: "<h2>DOUZIEME MAISON GEOMANCIQUE \"TRUKPIN-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m12.svg\"/><h2>Son signe: \"TRUKPIN\"</h2><img classname=\"page-image\" src=\"./geomancie/s12.svg\"/><p>En dignité dans la douzième maison, \"TRUKPIN-MEDJI\" est maître de celle-ci où il se trouve en puissance maximum. Son signe \"TRUKPIN\" qui correspond à la figure le \"Blanc\" est de prédominance Eau. Astrologiquement gouvernée par la planète Mercure, cette maison est dominée par le signe de la Vierge. En taromancie, elle correspond à l'arcane 6, \"L'AMOUREUX\".<p>La combinaison Mercure-Vierge qui vient accentuer les qualités dominantes de l'élément Eau, fait dispenser par celui-ci, une influence qu'on peut qualifier à juste titre de mitigée., parce que douteuse, c'est-à-dire ni bonne ni mauvaise. Aussi, appelle-t-on cette maison celle du doute, de l'hésitation, du manque de confiance envers soi et autrui. Cette maison prédispose donc le natif à l'hésitation et au doute. D'un caractère soupçonneux, le sujet est indécis et ne voit jamais les choses sous leurs angles réels. Les énergies inférieures libérées par cette maison donnent des qualités plus intellectuelles que pratiques, une nature plus intuitive que déductive et un caractère d'adaptabilité. Elle prédispose à une pureté morale, une haute intellectualité, tout ce qui élève l'esprit et l'âme, au mysticisme, à l'ésotérisme et à l'occultisme. Sur le plan pratique, la peur de l'effort et la crainte de se tromper, de tromper autrui ou de perdre ce qu'on a, en voulant l'améliorer, place le sujet dans une alternative permanente. Le natif est un pessimiste qui prend ses moindres difficultés pour des obstacles et ceux-ci pour des catastrophes. Il est d'un esprit trop analytique et critique: incapable de prendre des décisions, il est toujours insatisfait.<p>Dans le domaine matériel, l'état d'esprit du sujet le faisant sous-estimer ses possibilités, ceci constitue un handicap pour les entreprises de grande envergure, tout en lui faisant perdre d'heureuses occasions. Du point de vue des sentiments, cette maison est encore peu favorable, le sujet étant d'une extrême timidité ou d'une pudeur excessive; la méfiance, le souci du \"qu'en dira-t-on\" ou la crainte d'être incompris prouvent que le natif aime sans espoir et souffre en silence. Egalement peu favorable à la progéniture, elle prédispose la femme aux avortements ou prévoit la mort des enfants dans leur jeune âge.</p><br><p><strong>En consultation :</strong> cette maison ou son signe annonce une union ou un amour, signale une inconstance ou un amour inavoué. Indique parfois une union multiple pour le consultant; dans ce cas, elle trouve l'infidélité, la légèreté ou l'embarras devant un choix à faire. Annonce également un dommage pour le pour le malade ou pour le consultant. Pour une femme, c'est une grossesse non",
		  page_number: "113"
		},
		{
		  id: 24,
		  content: "désirée, un avortement ou une menace d'avortement. Elle prévoit en outrel'amour platonique ou louche qu'on n'ose avouer. Dans tous les cas, cette maison détermine un consultant inquiet, indécis ou dans l'embarras d'un choix à faire, ou d'une décision à prendre, prévient aussi des soucis de famille, des entreprises déraisonnables, une impuissance du consultant devant un problème, etc. <br><p><strong>Cette maison est en rapport avec :</strong> les maternités, les chapelles, les couvents, les expositions d'horticulture, les magasins de blanc, la neige, l'eau canalisée pour l'esthétique, la pureté, l'élevation morale, etc.</p><br><p><strong>Représente :</strong> les écrivains, les journalistes, compositeurs, aquarellistes, notaires, décorateurs, religieuses, libraires, els hommes d'affaires, les commerçants, les trompeurs, les nageurs, les enfants, les frères, les cabotins, les scribes, etc.</p><br><p><strong>Feuilles liturgiques :</strong> zùno (Fon)</p><br><p><strong>Couleur préférée :</strong> le rouge, le noir et les objets tâchetés.</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou les bonnes influences de cette maison ou de son signe, adresser les prières, cérémonies, sacrifices (Vonssissas ou Adras) aux divinités Sakpata, Na en y associant Hoho (jumeaux), Dan et Gu.",
		  page_number: "114"
		},
		{
		  id: 25,
		  content: "<h2>TREIZIEME MAISON GEOMANCIQUE \"TULA-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m13.svg\"/><h2>Son signe: \"TULA\"</h2><img classname=\"page-image\" src=\"./geomancie/s13.svg\"/><p>La troisième maison géomancique est gouvernée par \"TULA-MEDJI\". Son signe \"TULA\" s'y trouve en dignité et en puissance maximum. Il correspond à la figure la \"Fille\" encore nommée \"Puella\". Astrologiquement dominée par la planète Vénus et le signe du Taureau, son signe est de prédominance élementaire Eau. En taromancie, il correspond à l'arcane 4, \"L'EMPEREUR\".<p>Recevant les bons aspects de la planète Vénus et du signe de Taureau, l'élément Eau dispense dans cette treizième maison des influences bénéfiques. Cette maison prédispose le natif au bon sens: c'est un être positif. Le sujet a un esprit pratique, un caractère réaliste et un sens analytique plus déductif qu'intuitif. Persévérant, le natif que protège le destin connaitra un bonheur réel et relatif à son milieu. Cette maison prédispose favorablement le sujet à la gérance des affaires matérielles, pondérables, solides et durables, en accordant des satisfactions plus matérielles que spirituelles. D'un caractère affable, doux, le sujet très vénal a des tendances amoureuses très vives qui le portent vers les agréments de la vie, les mondanités, les plaisirs et les manifestations artistiques. En outre, il a des conceptions esthétiques. Nature d'eau influencée par Vénus, cette maison expose le natif à une inconstance et à une tendance aux plaisirs sexuels pouvant le conduire parfois à la débauche. Sur le plan matériel, cette maison est celle de la réussite dans les affaires matérielles, politiques et administratives. Le sujet bénéficiant de la protection et des appuis puissants dans les moments difficiles, est en outre favorablement disposé à l'exercice du pouvoir. Elle confère aux natifs des qualités de chefs, car ils sont de rudes adversaires, tenaces, imperméables et parfois même despotes. Imbu de ses prérogatives, le natif ou le consultant qui est un égoïste mais non un méchant, a un sens aigu de la légalité et de la respectabilité.<p>Du point de vue sentimental, cette maison, tout en étant favorable à l'union, cause des difficultés et amène parfois des déceptions du fait que le natif, inconstant dans ses affections, est coureur et volage. Physiquement, cette maison donne une grande résistance, mais avec l'âge, engendre des perturbations et des incommodités fort diverses, consécutives à des abus dans tous les domaines, même du travail et des plaisirs.</p><br><p><strong>En consultation :</strong> cette maison ou son signe désigne les lamentations, des difficultés d'entourage, de milieu ou dans le ménage et qui sont dues à la jalousie. Elle indique l'adultère qui coûte, une grossesse avancée ou adultérine.",
		  page_number: "115"
		},
		{
		  id: 26,
		  content: "<p>Le désir du changement ou le changement. Signale un empêchement pour un voyage, le malheur pour un prisonnier. Elle indique aussi les plaisirs, la gaîté et la luxure, une amère déception sentimentale pouvant parfois provoquer la démence ou tout au moins le délire. Elle prévoit un abus d'autorité, puis signale un protecteur, un homme puissant ou influent dont le concours ou les appuis sont utiles et indiquées dans une circonstance donnée. Un cadeau ou un présent , les biens passagers, une puissance passagère, ou bien dans la négative, la perte d'une domination, d'un bien, d'une puissance ou la chute de quelque chose. Le projet du consultant est voué au succès, malgré sa grande passivité.</p><br><p><strong>Cette maison est en rapport avec :</strong> les salles de spectacles, les galeries d'art, les salons de coutures et de modes. Les magasins de fleurs et d'objets de luxe, les choses ou les manifestations artistiques. Le calme, la paix, les fabricants de colifichets ou de parfum, etc.</p><br><p><strong>Représente :</strong> les musiciens, les chanteurs, les poètes, les esthéticiens, les administrateurs ou détenteurs de pouvoirs temporels, les coiffeurs, parfumeurs, couturiers, modélistes, mannequins, modistes, etc.</p><br><p><strong>Feuilles liturgiques :</strong> alafya ou fifama (fon)</p><br><p><strong>Couleur préférée :</strong> toutes les couleurs, mais semble se prononcer pour le bleu, le blanc, l'or et ce qui est tâcheté.</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou les bonnes influences de cette maison ou de son signe, adresser des sacrifices, prières, cérémonies (Vonssissas oou Adras) aux divinités Lègba, Dan, Liss, Tohossou et y associer Hoho (les jumeaux), Adjaguna et Gu (faire souvent des offrandes de nourritures \"Saara\" - Hênan - bla dangban).",
		  page_number: "116"
		},
		{
		  id: 27,
		  content: "<h2>QUATORZIEME MAISON GEOMANCIQUE \"LETE-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m14.svg\"/><h2>Son signe: \"LETE\"</h2><img classname=\"page-image\" src=\"./geomancie/s14.svg\"/><p>Seigneur de la quatorzième maison, \"LETE-MEDJI\" se trouve en dignité et en puissance maximum dans celle-ci qu'il gouverne. Son signe \"LETE\" correspond à la figure géomancique \"Puer\" encore nommée \"l'Enfant\", il est de prédominance élementaire Feu. Astrologiquement, cette maison et son signe sont régis par la planète Mars et le signe se Bélier. En taromancie, elle équivaut à l'arcane 11, \"LA FORCE\".<p>Cette maison et son signe font partie des plus redoutables de la géomancie. La combinaison des effets Mars-Bélier permet à l'élément Feu, dans cette quatorzième maison, de libérer des influences d'une force et d'une virulence exceptionnelles. Aussi, appelle-t-on à juste titre cette maison, celle de la force, et qui prédispose le natif à la possession de lui-même, à l'équilibre physique et moral. Elle est l'indication du triomphe assuré dans la lutte. Elle prédispose le sujet au courage, à la résistance physique tout en lui donnant des qualités expansives et excentriques comme la violence et la colère. D'un esprit chevaleresque, le natif est d'une franchise et d'une audace souvent brutales. Les instincts héréditaires dominent le sujet. Imbu d'une impulsivité et d'une vitalité difficiles à contenir, le natif agit avec fougue et irreflexion, puis épouse souvent les querelles d'autrui, ou s'occupe des choses qui ne le regardent pas.<p>Aussi, cette maison expose-t-elle aux heurts, aux difficultés et aux querelles d'entourage, à la lutte permanente parce que violent, irréfléchi, parfois agressif, le sujet agit souvent avec imprudence. Mais son caractère indépendant et batailleur , son esprit subtil et ingénieux lui permettent de triompher des difficultés et de renverser maints obstacles. Le natif est, par ailleurs, très viril, sensuel et autoritaire. Cette maison expose aux blessures morales ou physiques, à la mort violente et aux déplacements malheureux.<p>Sur le plan matériel, elle permet de réussir et de se faire un nom après des débuts souvent bien difficiles. Sentimentalement, elle permet un mariage heureux du fait que le natif est très viril et sensuel, mais indique des heurts et des affrontements dus à la passion. Très favorable à la santé, cette maison donne une abondance de sève vitale et un besoin de dépense physique.</p><br><p><strong>En consultation :</strong> cette maison ou son signe signale des difficultés et des ennuis dans la réalisation d'un projet ou du désir du consultant. Indique la volonté ou la possibilité de vaincre les évènements. Signale que le consultant sera maître de la situation ou viendra à bout de ses difficultés s'il a raison. Indique",
		  page_number: "117"
		},
		{
		  id: 28,
		  content: "<p>également des difficultés, des heurts et des affrontements d'entourage dans lesquels il exprime la colère ou le mécontentement. Indiique parfois des blessures données ou reçues, un accident , une bagarre, des disputes. Une domination ou la perte d'une domination, parfois une appréciation erronée du consultant, une guérison dans un cas de maladie. Mauvais augure pour les voyageurs, prévoit des brigands sur le parcours et des déprédations. Dans l'affirmative, c'est un avantage certain pour le consultant.</p><br><p><strong>Cette maison est en rapport avec :</strong> les dépôts d'armes, les jeux de cirque, les tavernes, les salles de boxe, les objets tranchants et pointus, les pierres rouges, les casernes, les endroits animés, la dictature, l'anarchie, les bruits, les industries métallurgiques, les usines, etc.</p><br><p><strong>Représente :</strong> les explorateurs, les soldats, les armuriers, les sportifs, les boxeurs, les chefs, les réunions d'officiers, de gouvernants, le pouvoir militaire, le mari, le fiancé ou l'amant. Les associés, les voyages, les révolutionnaires, les militaires, etc.</p><br><p><strong>Feuilles liturgiques :</strong> awiima, gninsikin, akaya, azonvoévoéma (fon)</p><br><p><strong>Couleur préférée :</strong> rouge, noir, gris, bleu, blanc</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou les bonnes influences de cette maison ou de son signe, adresser les cérémonies, prières, sacrifices (Vonssissas ou Adras) aux divinités Sakpata. Kinnessi et Na en y associant Hêbiosso et Gbadé.",
		  page_number: "118"
		},
		{
		  id: 29,
		  content: "<h2>QUINZIEME MAISON GEOMANCIQUE \"TCHE-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m15.svg\"/><h2>Son signe: \"TCHE\"</h2><img classname=\"page-image\" src=\"./geomancie/s15.svg\"/><p>\"TCHE-MEDJI\" commande la quinzième géomancique. Son signe \"TCHE\" s'y trouve en double, en dignité et en puissance maximum. Il correspond à la figure dénommée Perte ou Amissio. De prédominance élementaire Air, cette maison et son signe sont astrologiquement gouvernés par Jupiter et le signe de poisson. En taromancie, cela équivaut à l'arcane 12, \"LE PENDU\". Cette maison et son signe font partie des plus funestes et redoutables de la géomancie. Aussi, la tradition défend-elle de l'associer avec \"l'Enfant\", autre signe géomancique, ou de les nommer ensemble.<p>Recevant les mauvais effets de Jupiter et du signe des Poissons, l'élément Air libère et diffuse dans cette maison, les influences les plus funestes, néfastes, voire même redoutables. La mauvaise combinaison Air-Eau fait que cette maison donne au natif une très mauvaise prédisposition. Comme son nom l'indique bien, elle est vraiment la maison de la perte, car elle expose à une série d'épreuves contre lesquelles il est difficile de lutter. Elle indique l'échec par manque de but précis, le sujet dispersant ses forces dans des projets inutiles. Vélléitaire, le natif a tendance à réduire les projets d'une certaine envergure, ne prend jamais de repos, mais n'arrive pas non plus à réaliser tout ce qu'il entreprend. Cette maison indique la perte dans tous les domaines ou sous toutes ses formes, que ce soit du point de vue de la santé, des finances, des sentiments, ou des biens moraux. Maison de l'instabilité, elle prédispose le sujet à la déception, à l'inconstance, à la mollesse, à la tromperie, à la médisance avec pour cortège la duplicité, l'adultère, la versatilité, la paillardise et une certaine audace dans le mal. Cette maison marque surtout que tout ce qui se produit est le résultat des fautes du natif, et prescrit qu'il lui serait maintenant trop difficile de changer ou de se défendre; ayant déjà suivi pendant longtemps la mauvaise voie, l'heure du châtiment, de la punition intervient pour le faire payer. Elle prédispose au dénouement heureux des évènements, mais les multiples inconduites du natif l'exposent malheureusement aux désillusions et aux sacrifices pouvant aboutir à une regrettable fatalité, sans recours possible.<p>Dans la pratique de la géomancie astrologique, cette maison est, à juste titre, celle du juge. A cet effet, elle requiert la force morale pour l'acceptation, quel que soit le verdict du juge, d'un renversement de situation bonne ou mauvaise. Sur le plan matériel ou financier, elle expose aux pertes et aux déboires de toutes sortes, voire même la ruine. Sentimentalement, elle est encore défavorable, car elle entraîne des difficultés de tous genres dues à l'inconstance,",
		  page_number: "119"
		},
		{
		  id: 30,
		  content: "<p>au manque de fixité dans le désir, à l'adultère et à la duplicité. Physiquement, elle expose à des maladies graves dues à des excès dans tous les domaines.</p><br><p><strong>En consultation :</strong> cette maison ou son signe signale une désillusion, un sacrifice, une fatalité, puis indique des difficultés sentimentales, l'adultère qui coûte, le scandale, le divorce, la grossesse non désirée, une menace d'avortement, un accouchement pénible. Elle prévoit des dommages, des mensonges, une perte sans retour. Un veuvage, une menace de mort brutale du consultant ou d'un membre de son entourage. Un faux espoir, une vengeance de femmes, des attaques sournoises professionnelles ou concernant la vie privée. Un danger certain, une perte certaine dans un domaine comme dans un autre. Elle indique également que le consultant manque de libre arbitre moralement ou qu'il est emprisonné mentalement. Montre également un projet d'ordre sentimental dont la réussite sera boiteuuse, sans agrément ni plaisir, ou un projet caché, un manque de franchise, une réticence ou une hypocrisie. Dans tous les cas, c'est un abandon de quelque chose, une destruction, une condamnation ou une réprobation, un renforcement ou un projet douteux.</p><br><p><strong>Cette maison est en rapport avec :</strong> la disette, la pénurie, les images pornographiques, le recel, la campagne calomnieuse, les nuages, le vent, les lettres anonymes, les lieux malfamés, etc.</p><br><p><strong>Représente :</strong> les percepteurs, les huissiers, les tenanciers de maison de jeux, les croupiers. Indicateurs de police, scribes, cordonniers, les femmes légères, les escrocs, les pickpockets, les prodigues et les débauchés, ceux qui encaissent de l'argent, etc.</p><br><p><strong>Feuilles liturgiques :</strong> nukunzawé, hansimlin, azéloko, futukôdô (fon)</p><br><p><strong>Couleur préférée :</strong> ce signe n'a aucune préférence, mais en demande trois à la fois.</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les bonnes ou mauvaises influences de cette maison ou de son signe, adresser les prières, cérémonies, sacrifices (Vonssissas ou Adras) aux divinités Sakpata, Kinnessi, puis associer Hêbiosso, Lissa, Gu et Tohossou.",
		  page_number: "120"
		},
		{
		  id: 31,
		  content: "<h2>SEIZIEME MAISON GEOMANCIQUE \"FU-MEDJI\"</h2><img classname=\"page-image\" src=\"./geomancie/m16.svg\"/><h2>Son signe: \"FU\"</h2><img classname=\"page-image\" src=\"./geomancie/s16.svg\"/><p>La seizième et dernière maison géomancique est commandée par \"FU-MEDJI\". Son signe \"FU\" qui correspond à la figure Acquisition, s'y trouve en double, en dignité et en puissance maximum. De prédominance élementaire Air, ce signe est astrologiquement gouverné par la planète Jupiter et le signe de Sagittaire. En taromancie, il équivaut à l'arcane 5, \"LE PAPE\".<p>Contrairement à la maison précédente, celle-ci peut être appelée la maison de la bonne influence de l'élément Air. En effet, recevant les effets bénéfiques de la planète Jupiter en signe de Sagittaire, l'élément Air dispense dans cette maison des influences fastes, heureuses et salutaires. Cette maison prédispose le natif à la douceur, à la domination de lui-même, dénote un jugement sûr et lucide, puis le discernement. Elle représente les énergies bienfaisantes qui se regroupent pour atteindre un but non encore déterminé. Elle prédispose aussi à des changements avantageux ou transcendants, à un accroissement de gains ou de la fortune. Elle indique la puissance occulte de l'homme sur la matière. Elle détermine les qualités morales, intellectuelles et physiques. En outre, elle prédispose à la franchise, à la loyauté, à la bienfaisance, au dévouement, mais aussi à la sévérité. Elle expose à l'ambition, au souci de domination, de la hiérarchie, de la respectabilité et de l'égoïsme. Expose également aux luttes incessantes, aux dangers d'impulsions trop hâtives.<p>Sur le plan physique, cette maison donne un contrôle, un bon équilibre et une longévité probable. Matériellement, les biens terrestres s'acquièrent graduellement grâce à une action raisonnée, lente mais sûre, toujours orientée dans le sens du désir. L'ascension peut être lente mais inéluctable, apportant la considération, la respectabilité et parfois la gloire. Sentimentalement, cette maison n'apporte pas toujours l'espoir attendu du fait que le natif égoïste, épris de considération et de domination, est trop soucieux de sa respectabilité.</p><br><p><strong>En consultation :</strong> cette maison ou son signe annonce une joie, l'acquisition de quelque chose. Une grossesse attendue ou une naissance, une bonne délivrance, pour la femme enceinte. Indique le recouvrement d'une chose perdue, accroissement pour un bien, un larcin. Signale également les luttes dont on triomphe, les heurts avec l'entourage par souci de domination. Un secret dévoilé, une vocation confirmée, une puissance occulte. Parfois, elle indique un dommage pour un prisonnier ou un malade, l'empêchement pour un déplacement ou un",
		  page_number: "121"
		},
		{
		  id: 32,
		  content: "<p>projet retardé. Le plus souvent, indique une amélioration certaine de quelque chose, dans un domaine comme dans un autre. Signale un accroissement de gains ou une richesse. Favorable à la question posée.</p><br><p><strong>Cette maison est en rapport avec :</strong> les églises, les temples, les palais somptueux, les quartiers riches, aristocratiques, imposants. Les lieux de repos, les plages, préventoriums, sanatoriums, la fortune, l'expansion, les portefeuilles d'assurance, la suralimentation, les étables, les élevages, le pouvoir spirituel.</p><br><p><strong>Représente :</strong> les banquiers, boursiers, caissiers, commerçants de gros, fruitiers, financiers, employés de banque, directeurs, propriétaires de galeries d'art ou de grands magasins, le père adoptif riche, le parrain, le prêtre, le protecteur, l'ami puissant et fortuné, un haut fonctionnaire, le ministère, le gros négociant, une grossesse, un détenteur du pouvoir spirituel ou occulte, etc.</p><br><p><strong>Feuilles liturgiques :</strong> tutu, kodozo, zêhêma, adantôfio, sinfifaman</p><br><p><strong>Couleur préférée :</strong> le blanc - mais aucune autre couleur ne lui déplaît.</p><br><p><strong>Pour conjurer ou s'attirer :</strong> les mauvaises ou les bonnes influences de cette maison ou de son signe, adresser les prières, cérémonies, sacrifices (Vonssissas ou Adras) aux divinités Lissa, Mawu, Nan et y associer Odu, Dan, Hoho (les jumeaux), Sakpata et Hêbiosso.",
		  page_number: "122"
		},
		{
		  id: 33,
		  content: "<h2>CHAPITRE 2</h2><h2>SIGNIFICATION DES SIGNES GEOMANCIQUES</h2><p>Dans ce chapitre, nous allons vous donner la signification de chaque signe geomancique, sa nature et) toutes ses caractéristiques essentielles. Souvenez vous de ce que nous avions dit dans les chapitres précédents au sujet des maisons et des signes.<p>Les signes geomanciques sont ou désignent des types d'individus ou d'éléments. Autrement dit, le signe est le type d'individu au d'élément produit par une maison geomancique. A ce titre, ils sont comparables aux planètes dans l'astrologie et en cartomancie ; ils sont comme les arcanes a tête.<p>C'est le signe qui vous permettra de connaitre la nature profonde de l’individu ou de l'élément soumis au ­sondage ou a l'analyse de la geomancie. Dans la combinaison, il est l'élément dominant. Si la maison geomancique (de passation) vient jouer sur le signe en apportant des modifications et des nuances de par sa nature, il n'en demeure pas moins que le signe constitue l'élément principal de la combinaison. Son influence est donc prépondérante par le fait qu'il est l'élément dominant de la combinaison. Dans une combinaison, il est représenté a droite et s'enonce en premier lieu.",
		  page_number: "123"
		},
		{
		  id: 34,
		  content: "<h2>PREMIER SIGNE : \"OGBE\"</h2><h2>Figuration Indicielle</h2><img classname=\"page-image\" src=\"./geomancie/s1.svg\"/><p><strong>Sexe :</strong> masculin Signe de jour.<br> <strong>Nature :</strong> d' eau benefique, mais légèrernent défavorable. <br> <strong>Jour :</strong> lundi.<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Cancer.<br> <strong>Planète :</strong> Lune.<br><p><strong>Portrait physique :</strong> taille moyenne, corps épais dans sa partie supérieure­. Un oeil plus gros ou avec une tâche. Teint bronzé ou clair; dents petites, front moite.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> gouts ordinaires et simples. Inconstance, irreflexion, imagina­tion, timidité, inertie. Implique l'idée de pénétration et de recherche en pro­fondeur. Tendance au découragernent et manque de scrupules. Prudence dans les affaires d'argent. Libéral et plaisant, mais un peu paresseux. Mediumité, mobilité d'esprit, aimant les voyages, les déplacements.<br> <strong>Intellectuellement :</strong> esprit léger, étourdi, capricieux et bavard sans grande consistance. Calculateur sans tenacité. Indécision, impressionnabilité.<br> <strong>Professions :</strong> fonctionnaires, cultivateurs, employés de pompes funèbres, les poètes, les politiciens, les artistes mystérieux ou les écrivains mystiques. Toutes les professions féminines, surtout celles qui touchent les liquides ou qui demandent de l'imagination. Les· cheminots et tout ce qui s'apparente à la route cornme les transports, camionneurs, facteurs des P.T.T., mariniers, acteurs en tournée, routiers, colporteurs, cyclistes, etc.<p><strong>Rapport physique :</strong> les intestins.<p><strong>Maladies :</strong> diarrhées, anémies par lymphatisme, agitation stérile et fatigante, odorat, oeil gauche, intestins et tous les maux qui s’y rapportent. Dépression.",
		  page_number: "124"
		},
		{
		  id: 35,
		  content: "<h2>DEUXIEME SIGNE : \"YEKOU\"</h2><h2>Figuration Indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s2.svg\"/><p><strong>Sexe :</strong> féminin – Signe de nuit.<br> <strong>Nature :</strong> d’eau maléfique<br> <strong>Jour :</strong> lundi.<br><p><strong>Correspondance astrologique :</strong> <br> <strong>Signe du Zodiaque :</strong> Cancer <br> <strong>Planète :</strong> Lune.<p><strong>Portrait physique :</strong> taille harmonieuse, plutot élevée. Visage beau et bienveillant corps maigre. Jambes minces ; tâches sur un oeil ou un oeil plus gros. Teint brun. Dents longues, allure un peu soignée, cicatrice ou signe apparent.<p>Caracteres : <br> <strong>Moralement :</strong> versatilité, verbosité, capricieux, honnête et actif, accommodant mais indiscret. Bavard et moqueur. Peu sentimental, inconstant et passif. Soumission ; se laissant entrainer sans réfléchir. Décevant, sournois, hypocrite, aimant faire des choses en cachette. Porté à l'adultère ou à l'union double; parfois prostitution.<br> <strong>Intellectuellement :</strong> sens des foules et du calcul.<br> <strong>Professions :</strong> commis voyageurs et tous ceux dont le travail consiste à se deplacer continuellement. Les marins, les pêcheurs, camelots, forains, speakers, avocats. Tout ce qui a trait à la navigation ; le marché, le commerce, les chroniqueurs téléphonistes, etc.<br><p><strong>Rapport physique :</strong> Thorax<p><strong>Maladies :</strong> rhumes, bronchites, refroidissements, odorat, estomac. Poumons, troubles de nutrition, tumeurs cancéreuses, risques de noyade ou asphyxie.",
		  page_number: "125"
		},
		{
		  id: 36,
		  content: "<h2>TROISIEME SIGNE : \"WOLI\"</h2><h2>Figuration Indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s3.svg\"/><p><strong>Sexe :</strong> masculin - Signe de jour.<br> <strong>Nature :</strong> terre - neutre - Favorable.<br> <strong>Jour :</strong> mercredi<br><p><strong>Correspondance astrologique :</strong> <br> <strong>Signe du Zodiaque :</strong> Gémeaux <br> <strong>Planète :</strong> Mercure.<p><strong>Portrait physique :</strong> taille moyenne. Corps ni trop gros, ni trop maigre. Visage beau et ovale. Jambes fines. Bras et cuisses longs. Cheveux unis. Grâce et beauté.<p><strong>Caractères :</strong> <br> <strong>Moralement :</strong> honnête, obéissant, un peu timide. Etourderie et superficialité. Pénétration d'esprit, conception pratique permettant un jugement rapide de la valeur exacte des gens et des choses. Souplesse, argumentation et savoir-faire. Adaptabilité.<br> <strong>Intellectuellement :</strong> subtilité d'esprit- apte à tout faire - éloquence - ingéniosité- aptitude pour écrire.<br> <strong>Professions :</strong> orateurs, philosophes, compositeurs, écrivains talentueux, scientifiques, journalistes, industriels, jurisprudence, gens de lettres, diplomates, etc<br><p><strong>Rapport physique :</strong> système nerveux, poumons, ouïes et intestins.<p><strong>Maladies :</strong> maladies des voies respiratoires, du système nerveux et des intestins. Morsures d'animaux ou de pièges pour gros gibiers.",
		  page_number: "126"
		},
		{
		  id: 37,
		  content: "<h2>QUATRIEME SIGNE : \"ODI\"</h2><h2>Figuration Indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s4.svg\"/><p><strong>Sexe :</strong> féminin<br> <strong>Nature :</strong> Terre - maléfique<br> <strong>Jour :</strong> samedi<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Capricorne <br> <strong>Planète :</strong> Saturne <br><p><strong>Portrait physique :</strong> taille moyenne, plutôt petite. Forte ou grosse tête, bras courts, teint mât, fortes mâchoires, cheveux rudes, cou épais, visage rond, yeux sanguinolents.<p>Caractère : <br> <strong>Moralement :</strong> caractère dur, sévère, opinâtre, mélancolique et misanthrope. Egoïste et avare, aimant l'argent; restriction, manque de cordialité, méprisé et quelquefois haï. Difficultés d'entourage, entraves, contrainte morale et physique. Jeunesse difficile. Humiliations et servitudes. <br> <strong>Intellectuellement :</strong> réflexion, ne se décide que lentement. Concentration, plus d'intérêt pour le passé que l'avenir. Intelligence pénétrante et persévérance dans le travail. Préfère la ruse à la violence. Prudence et modération. <br> <strong>Professions :</strong> ingénieurs, chimistes, mathématiciens, astrologues, astronomes, géoliers, fossoyeurs, mineurs, gardiens de nuit, policiers, fonctionnaires sédentaires, archivistes, espions, etc. <br><p><strong>Rapport physique :</strong> tact, estomac, rate, pieds, os.<p><strong>Maladies :</strong> rhumatismes, constipation, varices, leucémie, fractures, troubles cutanés.",
		  page_number: "127"
		},
		{
		  id: 38,
		  content: "<h2>CINQUIEME SIGNE : \"LOSSO\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s5.svg\"/><p><strong>Sexe :</strong> masculin - Signe de jour <br> <strong>Nature :</strong> feu - Peu favorable <br> <strong>Jour :</strong> dimanche <br><p><strong>Correspondance astrologique :</strong> <br> <strong>Signe du Zodiaque :</strong> Lion <br> <strong>Planète :</strong> Soleil <br><p><strong>Portrait physique :</strong> taille petite ou plutôt moyenne. Maigre ou quelque fois léger embonpoint. Visage rond, teint clair ou bronzé. Nez effilé, yeux noirs souvent baissés; front large, marque au visage ou signe apparent à l'oeil droit.<p><strong>Caractères :</strong> <br> <strong>Moralement :</strong> égoïste et irrascible. Large pour lui-même et sans géné1rosité pour autrui. Prompt à la colère. Brusquerie poussant à agir sans réfléchir. Prodigue, présomptueux et malheureux en amour. Fâcheries, jalousies, satisfactions suivies de revers, fréquents ennuis, unions multiples, dépit amoureux. <br> <strong>Intellectuellement :</strong> nombreuses connaissances superficielles dans tous les domaines et souvent mal utilisées. <br> <strong>Professions :</strong> propagandistes, politiciens, pionniers, joailliers, directeurs d'entreprises et métiers comportant une direction, etc.<br><p><strong>Rapport physique :</strong> vue, cerveau et tête.<p><strong>Maladie :</strong> maladie de la moëlle épinière, douleurs de la colonne vertébrale. Troubles ou fatigues mentales, foie.",
		  page_number: "128"
		},
		{
		  id: 39,
		  content: "<h2>SIXIEME SIGNE : \"WINLIN\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s6.svg\"/> <p><strong>Sexe :</strong> féminin-Signe de jour. <br> <strong>Nature :</strong> feu bénéfique. <br> <strong>Jour :</strong> dimanche. <br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Lion.<br> <strong>Planète :</strong> Soleil.<br></p> <p><strong>Portrait physique :</strong> taille moyenne, couleur vermeille, visage rond, grands yeux, cheveux frisés, parties du corps supérieures plus grandes que les inférieures.</p> <p><strong>Caractères :</strong> <br> <strong>Moralement :</strong> caractère noble et généreux. Loyauté ostentatoire, magnanime. Sentiments élevés et grande maîtrise, courage, amour du pouvoir et de l'autorité. Charitable mais ambitieux et vindicatif; recherche les honneurs dans mains domaines. Egoïsme. <br> <strong>Intellectuellement :</strong> esprit de synthèse, sens politique, nombreuses connaissances dans le domaine du savoir. Intelligence, tact et savoir-faire.<br> <strong>Professions :</strong> acteurs célèbres, archéologues, antiquaires, hauts fonctionnaires, hommes illustres, hauts dignitaires, etc.<br></p> <p><strong>Rapport physique :</strong> vue, oeil droit, cou.</p> <p><strong>Maladies :</strong> conjonctivite, strabisme, rhumatismes, troubles de circulation - maladie bleue des enfants.</p>",
		  page_number: "129"
		},
		{
		  id: 40,
		  content: "<h2>SEPTIEME SIGNE : \"ABLA\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s7.svg\"/><p><strong>Sexe :</strong> masculin - Signe de nuit. <br> <strong>Nature :</strong> Air - Bénéfique. <br> <strong>Jour :</strong> Vendredi <br><p><strong>Correspondance astrologique :</strong> <br> <strong>Signe du Zodiaque :</strong> Balance. <br> <strong>Planète :</strong> Vénus <br><p><strong>Portrait physique :</strong> haute taille. Bien proportionné dans ses membres, visage rond, grandes dents ou manquantes à la mâchoire supérieure. Grands yeux, front large, cheveux rudes, cou épais, larges narines, nez fort.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> caractère paisible, amical, bienveillant - Enthousiasme, gaîté, insouciance et libéralisme. Habile, altruiste, honnête, mais parfois présomptueux. Inconstance dans tous les dommaines, surtout sentimentaux. <br> <strong>Intellectuellement :</strong> esprit gai, optimiste. Instruction superficielle, mais aptitude à réussir sans gros efforts, grâce à l'aide des amis, aimant la variété, fond nonchalent.<br> <strong>Professions :</strong> éditeurs, trésoriers, caissiers, organisateurs de fêtes, hauts clergés, magistrature, sportifs, restaurateurs, sociétés de bienfaisance, professeurs, etc.<br><p><strong>Rapport physique :</strong> ouïe, foie, poumons.<p><strong>Maladies :</strong> congestions pulmonaires, troubles circulatoires, maux infectieux, excès sportifs.",
		  page_number: "130"
		},
		{
		  id: 41,
		  content: "<h2>HUITIEME SIGNE : \"AKLAN\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s8.svg\"/><p><strong>Sexe :</strong> féminin - Signe de nuit <br> <strong>Nature :</strong> Terre - maléfique <br> <strong>Jour :</strong> Samedi <br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Verseau<br> <strong>Planète :</strong> Saturne<br><p><strong>Portrait physique :</strong> corps long et mince ou plutôt maigre. Teint mat. Dents allongées visage ovale, allure peu soignée. Signe au talon, cheveux rudes.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> caractère inquiet, mais bonnes moeurs. Tardif et lent en affaires. Solitaire, misanthrope, pessimiste et se repliant sur lui-même; tendance au découragernent, contrainte mélancolique, ne riant que rarement, et surtout très avare. Spleen. Ne vivant que dans les souvenirs et rarement au temps présent. Difficultés sentimentales, surtout dans les amours.<br> <strong>Intellectuellement :</strong> cerveau inquisiteur, scrupuleux, persévérant; aptitude à découvrir les choses cachées - mysticisme et occultisme.<br> <strong>Professions :</strong> archéologues, spéléologues, métaphysiciens, savants, physiciens. Philatélistes, mineurs, philosophes, moines, linguistes, agents secrets, policiers, etc.<br><p><strong>Rapport physique :</strong> toucher, système endocrinien.<p><strong>Maladies :</strong> troubles glandulaires, paralysie, rhumatismes, accident par la foudre ou électricité. Vue.",
		  page_number: "131"
		},
		{
		  id: 42,
		  content: "<h2>NEUVIEME SIGNE : \"GUDA\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s9.svg\"/><p><strong>Sexe :</strong> masculin - Signe de jour.<br> <strong>Nature :</strong> Terre - Maléfique.<br> <strong>Jours :</strong> mardi-samedi<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Taureau-Scorpion<br> <strong>Planètes :</strong> Vénus-Mars.<br><p><strong>Portrait physique :</strong> corps un peu disproportionné, visage allongé ou ovale, menton pointu. Larges mâchoires, jambes fortes, gros traits.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> caractère porté aux querelles, Fourberie, perversité, envie, mensonge et calomnie. Aime la magie noire, l'occultisme et la sorcellerie. Prodigue, utilisant des moyens douteux pour avoir de l'argent. Trahison, dissipation, perfidie et paresse. Tendance à se perdre dans les détails. Ennuis et tourments dans tous les domaines; soucis et ennuis sentimentaux. Adultère - Infidélité - Malheureux en amour.<br> <strong>Intellectuellement :</strong> ruse, goût de pervertir autrui.<br> <strong>Professions :</strong> chimistes, mineurs, fondeurs, serruriers, détectives, agents secrets, espions, entremetteurs, proxénètes, etc.<br><p><strong>Rapport physique :</strong> odorat, nez, organes virils.<p><strong>Maladies :</strong> maux vénériens, polypes, sinusites, hémorragies, intoxications, végétations. Faiblesse, déchéance, frigidité ou impuissance sexuelle.",
		  page_number: "132"
		},
		{
		  id: 43,
		  content: "<h2>DIXIEME SIGNE : \"OSA\"</h2><h2>Figuration indicielle:</h2><img classname=\"page-image\" src=\"./geomancie/s10.svg\"/><p><strong>Sexe :</strong> féminin - Signe de jour<br> <strong>Nature :</strong> Air-Bénéfique<br> <strong>Jour :</strong> Vendredi<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Gémeaux-Sagittaire<br> <strong>Planètes :</strong> Mercure-Jupiter<br><p><strong>Portrait physique :</strong> beau visage de forme ronde, Taille moyenne, grand nez, bouche large, dents longues - Beaucoup de cheveux<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> caractère grave, paisible, compatissant, aimmant les distractions sérieuses. Ambition, équilibre, honnêteté, prudence et respectabilité. Nonchalance.<br> <strong>Intellectuellement :</strong> esprit à l'éloquence convaincante. Imagination créatrice, esprit inventif et fécond. Apte à remplir des emplois importants. Assimilation facile. Richesse intellectuelle.<br> <strong>Professions :</strong> pilotes d'essai, aviateurs, pharmaciens, jardiniers, vignerons, entrepreneurs, guides, architectes, etc.<br><p><strong>Rapport physique :</strong> foie, organes génitaux féminins, matrice.<p><strong>Maladies :</strong> fibromes, gastrites, dysepsies, infections par l'eau.",
		  page_number: "133"
		},
		{
		  id: 44,
		  content: "<h2>ONZIEME SIGNE : \"KA\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s11.svg\"/><p><strong>Sexe :</strong> masculin - Signe de nuit<br> <strong>Nature :</strong> Feu - Maléfique<br> <strong>Jour :</strong> mardi<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Scorpion<br> <strong>Planète :</strong> Mars<br><p><strong>Portrait physique :</strong> visage anguleux - Aspect rude. Teint clair ou brun, parfois semé de tâches, de rougeurs ou de boutons. Voix forte et menaçante. Regard cruel et parfois mauvais. Signe en quelque partie du corps.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> beaucoup de qualités, mais mal employées dans le but de détruire ou exagérées, ce qui les transforme en défauts. Agressivité, impétuosité, colère, désobéissance et indiscipline. Nombreuses luttes sans grand résultat. Violence, impulsivité, emballement et passion. Heurts et brouilles fréquents avec l'entourage.<br> <strong>Intellectuellement :</strong> esprit rusé, critique; habileté au maniement de tout ce qui est tranchant. Esprit désinterressé, mais souvent tourné vers le mal. <br> <strong>Professions :</strong> ingénieurs, métallurgistes (aujourd'hui métalliers), céramistes, émailleurs, mécaniciens, souffleurs de verre, ferronniers, polémistes, officiers, novateurs, chasseurs, bouchers, etc.<br><p><strong>Rapport physique :</strong> vue - poitrine.<p><strong>Maladies :</strong> plaies, maux infectieux - opérations (chirurgicales) - Eruptions diverses - Congestions",
		  page_number: "134"
		},
		{
		  id: 45,
		  content: "<h2>DOUZIEME SIGNE : \"TRUKPIN\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s12.svg\"/><p><strong>Sexe :</strong> féminin - Signe de nuit.<br> <strong>Nature :</strong> d'eau, peu favorable.<br> <strong>Jour :</strong> mercredi<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Vierge<br> <strong>Planète :</strong> Mercure<br><p><strong>Portrait physique :</strong> taille petite, plutôt moyenne. Visage rond, grosse ou forte tête. Corps plus ample dans sa partie supérieure - front souvent moite. Peau épaisse . Petits yeux et signe sur un oeil; grande bouche, cheveux frisés.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> caractère honnête et affable. Indécision, hésitation et chagrin. Recherche de la pureté. Très compatissant. Préfère à tout prix la concorde. Paisible, joyeux mais réservé. Soucis et ennuis sentimentaux, surtout dans les amours, aimant l'occultisme.<br> <strong>Intellectuellement :</strong> esprit studieux, goût des arts, aptitudes artistiques, chance au jeu.<br> <strong>Professions :</strong> écrivains, journalistes, compositeurs, libraires, décorateurs, notaires, horticulteurs, réligieuses, nageurs, miroitiers, etc.<br> <strong>Rapport physique :</strong> gorge, bras, épaules, intestins.<br> <strong>Maladies :</strong> ouïes, entrailles (intestins), ptoses, inflammations diverses. Tumeurs graves ou bénignes. Stérilité. Rhumatismes.<br>",
		  page_number: "135"
		},
		{
		  id: 46,
		  content: "<h2>TREIZIEME SIGNE : \"TULA\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s13.svg\"/><p><strong>Sexe :</strong> masculin - Signe de jour.<br> <strong>Nature :</strong> d'eau - Bénéfique.<br> <strong>Jour :</strong> vendredi.<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Taureau<br> <strong>Planète :</strong> Vénus<br><p><strong>Portrait physique :</strong> de faible complexion, taille moyenne, corps harmonieux. Un peu gras. Visage beau, un peu empâté. Teint brun ou rouge. Petits yeux. Assez beau, effeminé. Charme.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> caractère paisible, courtois et affable. Inconstant et volage, surtout dans les sentiments. Tempérament très amoureux, tendance à l'ironie et à la moquerie. Graves ennuis et déboires sentimentaux dans les amours particulièrement. Adultère, infidélité, union double, parfois débauche.<br> <strong>Intellectuellement :</strong> sens artistique très développé. Goût des arts, aptitude pour la gérance, la politique et l'administration.<br> <strong>Professions :</strong> musiciens, chanteurs, poètes, esthéticiens, coiffeurs, parfumeurs, couturiers, modistes, modelistes. Mannequins - Cuisiniers - Religieuses - Artistes - Vendeuses.<br><p><strong>Rapport physique :</strong> visage - Bras, reins, seins-épaules - Gorge.<p><strong>Maladies :</strong> maux vénériens (troubles génitaux - urinaires ou vénériens) - Ganglions.",
		  page_number: "136"
		},
		{
		  id: 47,
		  content: "<h2>QUATORZIEME SIGNE : \"LETE\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s14.svg\"/><p><strong>Sexe :</strong> féminin - Signe de jour.<br> <strong>Nature :</strong> Feu - un peu défavorable.<br> <strong>Jour :</strong> mardi.<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Bélier.<br> <strong>Planète :</strong> Mars.<br><p><strong>Portrait physique :</strong> taille moyenne, corps robuste. Tête forte, cou long, visage rond, beau regard, sourcils bien dssinés; petite bouche, voix douce pouvant devenir mauvaise. Larges épaules. Léger embonpoint. Beauté et force. Abondance de sève vitale.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> caractère porté aux disputes et aux querelles - Colères violentes. Instinct de possession, de domination. Désirs sensuels puissants. Goûts révolutionnaires. Emballement, agitation, désordre et activisme. Confiance en soi, courage et même audace, puis sarcasme. Passion - Virilité - Heurts fréquents et brouilles avec entourage, pour raison d'intérêt.<br> <strong>Intellectuellement :</strong> esprit ingénieux, subtil, aimant la force et même la violence. Très critique, même polémique. Esprit indépendant, autoritaire et opiniâtre.<br> <strong>Professions :</strong> explorateurs, militaires, armuries, sportifs, boxeurs.<br><p><strong>Rapport physique :</strong> tête, vue, nuque, viscères.<p><strong>Maladies :</strong> congestion du foie, de la vésicule biliaire. Abcès. Accidents et blessures à la tête ou au visage",
		  page_number: "137"
		},
		{
		  id: 48,
		  content: "<h2>QUINZIEME SIGNE : \"TCHE\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s15.svg\"/><p><strong>Sexe :</strong> masculin - Signe de nuit.<br> <strong>Nature :</strong> d'air - Maléfique<br> <strong>Jour :</strong> jeudi.<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Poisson<br> <strong>Planète :</strong> Jupiter<br><p><strong>Portrait physique :</strong> taille moyenne, plutôt petite. Constitution solide, cou long. Assez forte tête. Larges épaules. Visage rond. Petite bouche. Beaux yeux - Belle chevelure, quelquefois une cicatrice ou une défectuosité de certaines parties du corps.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> tempérament impulsif. Vaniteux. Aucune volonté pour résister à ses propres désirs. Volage et inconstant, notamment dans les sentiments. Découragement, négligence, prodigalité et versatilité. Duplicité. Adultères, mensonges, tromperies et une certaine audace dans le mal. L'entêtement dans l'erreur, graves soucis amoureux. Libertinage et désillusions sentimentaux.<br> <strong>Intellectuellement :</strong> esprit brouillon, dissipateur. Attirance pour les amours avec des personnes inférieures.<br> <strong>Professions :</strong> percepteurs, huissiers, tenancies de maison de jeu. Croupiers - Indicateurs de police - Scribes - Cordonniers, etc.<br><p><strong>Rapport physique :</strong> vue, système nerveux, reins, épigastre.<p><strong>Maladies :</strong> blessure à l'oeil ou perte d'un oeil par accident. Blessure à la tête ou au visage. Troubles psychiques par excès - Epigastre et reins.",
		  page_number: "138"
		},
		{
		  id: 49,
		  content: "<h2>SEIZIEME SIGNE : \"FU\"</h2><h2>Figuration indicielle :</h2><img classname=\"page-image\" src=\"./geomancie/s16.svg\"/><p><strong>Sexe :</strong> féminin - Signe de nuit.<br> <strong>Nature :</strong> d'air - Bénéfique.<br> <strong>Jour :</strong> jeudi.<br><p><strong>Correspondance astrologique :</strong><br> <strong>Signe du Zodiaque :</strong> Sagittaire<br> <strong>Planète :</strong> Jupiter<br><p><strong>Portrait physique :</strong> taille moyenne, grosse ou forte tête. Visage aux traits menus et réguliers, figure plaisante. Un nez long ou effilé, cheveux abondants et frisés. Beau regard, grands yeux volontiers abaissés. Les dents de devant plus grandes que les autres. Les épaules étroites. Grande élégance.<p><strong>Caractères :</strong><br> <strong>Moralement :</strong> caractère sage, imposant, splendide pour sa dépense et par la bouche, mais avare quant au reste. Sens libéral; réflexion et patience. Egoïsme sentimental. Réussite matérielle ou financière.<br> <strong>Intellectuellement :</strong> sens des affaires et des spéculations. Aptitudes particulières pour le commerce et la politique. Dons d'organisateur. Enrichissement intellectuel, lucidité. Discernement.<br> <strong>Professions :</strong> financiers, employés de banque, directeurs ou métiers comportant une direction. Boursiers, caissiers, commerçants en gros, fruitiers, propriétaires ou gérant de grands magasins ou galeries d'art, etc.<br><p><strong>Rapport physique :</strong> ouïe - Vésicule biliaire - Ventre.<p><strong>Maladies :</strong> fièvre, congestions, plaies suppurantes, affections hépatiques, obésité. Accidents de circulation parmauvaise audition. Noyades par congestion.",
		  page_number: "139"
		}
	];

  
  const pagesList = pagesData.map((pageData: any, index: number) => {
							const t_text = parse(pageData.content);
							return (
								<Paper className="page"  key={index}>
									<div className="page-content">
										<div className="page-text">{parse(pageData.content)}</div>
										<Divider />
										<div className="page-footer">{pageData.page_number}</div>
									</div>				
								</Paper>
							)
						}	
					)
  //console.log(pagesList);
  
  const myStyle : React.CSSProperties = {};
  
  return (
    <>
      <Meta title="page 1" />
      
	  <div className="book-wrapper">
        <HTMLFlipBook width={300} height={1500}
		    size="stretch"
            minWidth={315}
            maxWidth={1000}
            minHeight={400}
            maxHeight={1533}
            maxShadowOpacity={1}
            showCover={true}
            mobileScrollSupport={true}
			drawShadow={true}
			flippingTime={1000}
			usePortrait={true}
			startZIndex={0}
			startPage={startPage}
			autoSize={true}
			swipeDistance={30}
			clickEventForward={true}
			useMouseEvents={true}
			disableFlipByClick={false}
			showPageCorners={true}
			style={myStyle}
			className="html-book"
            >
			<Paper className="page page-cover page-cover-top" data-density="hard">
				<div className="page-content">
					<Typography variant="h2">TITLE</Typography>
				</div>
			</Paper>
			
			{pagesList}
			
			<Paper className="page page-cover page-cover-bottom" data-density="hard">
				<div className="page-content">
					<Typography variant="h2">THE END</Typography>
				</div>
			</Paper>
			
        </HTMLFlipBook>
      </div>
    </>
  );
}

export default Page1;
